clear all; close all; clc; tic;

%% Environment
addpath('P1_stuff');

%% Load data : data_X are 3D points and data_x are 2D points
load data_X_and_x;

%% P1a
[ data_X_Homo, data_x_Homo, projMat, x_proj1, sse1 ] = getProjMat( data_X, data_x );

%% Draw P1a
%drawPoints;

%% P1b
KR = projMat(:, 1:3);
[K, R] = RQ_Decomp( KR );
R = R*K(3,3);
K = K/K(3,3); %K的(3,3)必須是1
Kt = projMat(:, 4);
t = K \ Kt; %K

%% P1c
x_proj2 = K* [ R, t ] * data_X_Homo ;
x_proj2 = x_proj2 ./ repmat(x_proj2(3,:), [3,1]) ;
sse2 = norm( x_proj2(1:2, :) - data_x ) ^2 ;

toc;

%% Print error
mse1 = sse1/size(data_x,2);
rmse1 = mse1^0.5;
fprintf ( 'SSE , MSE, RMSE generated by P1(a) : %.10f , %.12f , %.10f\n', sse1, mse1, rmse1 );

mse2 = sse2/size(data_x,2);
rmse2 = mse2^0.5;
fprintf ( 'SSE , MSE, RMSE generated by P1(b) : %.10f , %.12f , %.10f\n', sse2, mse2, rmse2 );

fprintf ( 'Error differences between P1(a) & P1(b) : %.10f , %.10f , %.10f\n', abs(sse1-sse2), abs(mse1-mse2), abs(rmse1-rmse2) );